name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

  download:
    runs-on: uubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.1.0
        with:
          name: hello.txt
      - name: Get File Output
        run: cat ./artifacts/hello.txt
